backend:
  name: github
  repo: Srppa/BrainVRDemo
  branch: main

  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI
    label_singular: "Project" # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { 
          label: "SEO Description",
          name: "description",
          widget: "string",
          hint: "Short description",
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
          tagname: "",
          hint: "picture that will be shown on project list tag, to be shown properly picture should be in 7:5 ratio",
        }
      - {
          label: "Is active project?",
          name: "isActive",
          widget: "boolean",
          hint: "is true then section with info to participate will be shown, i.e. contact name, contact email, contact email header MUST be filled",
        }
      - {
        label: "Contact Name",
        name: "contactName",
        widget: "string",
        hint: "Contact name",
        required: false,
        }
      - {
        label: "Contact Email",
        name: "contactEmail",
        widget: "string",
        hint: "Contact email",
        required: false,
        }
      - {
        label: "Contact Email Header",
        name: "contactEmailHeader",
        widget: "string",
        hint: "Header of email that will in prewrriten when contact email will be generated",
        required: false,
        }
      - {
        label: "Body",
        name: "body",
        widget: "markdown",
        hint: "Main content goes here.",
        }
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI
    label_singular: "Actuality" # Used in the UI, ie: "New Post"
    description: >
      Hre you can create and edit news section [aktuality].
    folder: "src/content/news"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
        label: "Template",
        name: "template",
        widget: "hidden",
        default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
        label: "Slug",
        name: "slug",
        widget: "string",
        hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
        label: "Publish Date",
        name: "date",
        widget: "datetime",
        dateFormat: "YYYY-MM-DD",
        timeFormat: "HH:mm",
        format: "YYYY-MM-DD HH:mm",
        }
      - { 
          label: "SEO Description",
          name: "description",
          widget: "string",
          hint: "Short description",
        }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        required: false,
        tagname: "",
        hint: "picture of actuality that will be shown on thumnail in news list and on homepage, to be properly shown it shoud be in 1:1 ratio",
        }
      - {
        label: "Body",
        name: "body",
        widget: "markdown",
        hint: "Main content goes here.",
        }
  - name: "members" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Members" # Used in the UI
    label_singular: "Member" # Used in the UI, ie: "New Post"
    description: >
      Here you can create and edit memberes section [Tým].
    folder: "src/content/team"
    slug: "{{slug}}"
    summary: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
        label: "Template",
        name: "template",
        widget: "hidden",
        default: "team-member",
        }
      - { label: "Name", name: "title", widget: "string", tagname: "h1" }
      - {
        label: "Slug",
        name: "slug",
        widget: "string",
        hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases. Must unique",
        }
      - { 
          label: "SEO Description",
          name: "description",
          widget: "string",
          hint: "Short description",
        }
      - {
        label: "Order",
        name: "order",
        widget: "number",
        value_type: "int",
        hint: "Order number, number 1 mean that it will be put first in team list. If one or more team members have same number than it's sorted alphabetically",
        }
      - {
        label: "Category",
        name: "category",
        widget: "select",
        options: ["core", "external", "alumni"],
        hint: "Category of team member [jádro, externí, alumni]",
        }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        required: false,
        tagname: "",
        hint: "Picture of team member, to be properly shown it shoud be in 1:1 ratio with face in center",
        }
      - {
        label: "Body",
        name: "body",
        widget: "markdown",
        hint: "Main content goes here.",
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "CTA text"
                widget: "string"
              - name: "ctaLink"
                label: "CTA Link"
                widget: "string"
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: image
                name: iconimage
                label: favicon
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - label: Social Icons
        name: socialIcons
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Icons
            name: socialIcons
            widget: list
            collapsed: true
            hint: "Here you can add social icons, Click on 'Add social icons'"
            fields:
              - label: "Icons"
                name: "icon"
                widget: "select"
                options:
                  [
                    "facebook",
                    "twitter",
                    "linkedin",
                    "youtube",
                    "instagram",
                    "rss",
                    "github",
                    "telegram",
                    "pinterest",
                    "snapchat",
                    "skype",
                    "wordpress",
                    "tiktok",
                    "dribbble",
                    "medium",
                    "behance",
                    "vk",
                  ]
                hint: "Select the Icon"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"